In [68]:
#experimental: 김명신. (2007). 온라인 쇼핑몰 소비자들의 구매 시 e-Satisfaction에 영향을 미치는 요인 대한 연구. 한국디자인포럼, 16, 93-101.
experimental = "This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had position effect on e-satisfaction. this implies that e-shoppers feel highly satisfied with the freedom of time and space which wall defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumers e-satisfaction. And the fact that consumers have tendency to trust more the shopping mall where they purchased more than once in the past means that transaction security also requires special consideration. This study was investigated with focused on shopping mall site itself, therefore the major parts of critical success factors from site design to implementation could be discussed and get helpful suggestions."
#comparision: 김영진. (2002). 인터넷 쇼핑몰에서 e-Satisfaction 에 영향을 주는 요인 연구. 석사학위논문, 한국외국어대학교, 서울.
comparision = "This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market; especially the survey was strictly carried out only for the consumers who had ever experienced e-shopping or transaction more than once. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had positive effect on e-satisfaction. This implies that e-shoppers feel highly satisfied with the freedom of time and space which was defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumer's e-satisfaction. And the fact that consumers have tendency to trust more the shopping mall where they purchased more than once in the past means that transaction security also requires special consideration. This study was investigated with focused on shopping mall site itself, therefore the major parts of critical success factors from site design to implementation could be discussed and get helpful suggestions."

In [56]:
experimental

'This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had position effect on e-satisfaction. this implies that e-shoppers feel highly satisfied with the freedom of time and space which wall defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumers e-satisfaction. And the fact that consumers have tendency to trust more the shopping mall where they purchased more than once in the past means that trans

In [57]:
comparision

"This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market; especially the survey was strictly carried out only for the consumers who had ever experienced e-shopping or transaction more than once. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had positive effect on e-satisfaction. This implies that e-shoppers feel highly satisfied with the freedom of time and space which was defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumer's e-satisfaction. A

In [58]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [59]:
comparision_cv = cv.fit_transform([comparision])
comparision_cv

<1x123 sparse matrix of type '<class 'numpy.int64'>'
	with 123 stored elements in Compressed Sparse Row format>

In [60]:
cv.get_feature_names_out()

array(['addition', 'additional', 'affect', 'affecting', 'also', 'analyze',
       'and', 'appropriate', 'as', 'assortment', 'availability', 'be',
       'been', 'carried', 'commerce', 'consideration', 'consumer',
       'consumers', 'convenience', 'could', 'critical', 'defined',
       'design', 'detailed', 'detected', 'discussed', 'diversity',
       'effect', 'especially', 'ever', 'experienced', 'fact', 'factor',
       'factors', 'fast', 'feel', 'focused', 'for', 'formed', 'freedom',
       'from', 'functions', 'general', 'get', 'had', 'has', 'have',
       'helpful', 'highly', 'if', 'implementation', 'implies', 'in',
       'information', 'internet', 'inventory', 'investigate',
       'investigated', 'is', 'it', 'itself', 'level', 'local', 'major',
       'mall', 'malls', 'market', 'means', 'more', 'of', 'offering', 'on',
       'once', 'online', 'only', 'or', 'other', 'out', 'parts', 'past',
       'performed', 'positive', 'product', 'products', 'proved',
       'purchased', 'requ

In [61]:
comparision_cv.toarray()

array([[1, 1, 1, 1, 3, 1, 8, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 1,
        2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
        2, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 3, 2,
        1, 2, 3, 9, 1, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1,
        3, 2, 1, 1, 1, 1, 6, 4, 1, 1, 1, 3, 1, 1, 2, 1, 1, 2, 5, 8, 1, 1,
        3, 1, 1, 5, 2, 1, 4, 1, 1, 1, 1, 1, 2]], dtype=int64)

In [62]:
experimental_cv = cv.transform([experimental])
experimental_cv

<1x123 sparse matrix of type '<class 'numpy.int64'>'
	with 110 stored elements in Compressed Sparse Row format>

In [63]:
experimental_cv.toarray()

array([[1, 1, 1, 1, 3, 1, 8, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 3, 2, 1, 1, 1,
        2, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 3, 1, 2, 2, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 3, 2,
        1, 2, 2, 9, 1, 4, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 3, 1, 1, 1, 1, 1,
        3, 2, 1, 1, 1, 1, 5, 4, 1, 1, 0, 3, 1, 1, 2, 0, 1, 1, 5, 6, 1, 1,
        3, 1, 1, 5, 1, 1, 2, 1, 1, 1, 1, 0, 2]], dtype=int64)

In [64]:
from sklearn.metrics.pairwise import cosine_similarity

In [65]:
result_cv_cosine = cosine_similarity(experimental_cv, comparision_cv)
result_cv_cosine

array([[0.9783011]])

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
comparision_tf = tf.fit_transform([comparision])
experimental_tf = tf.transform([experimental])

In [67]:
result_tf = cosine_similarity(experimental_tf, comparision_tf)
result_tf

array([[0.9783011]])