In [1]:
text1 = "This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had position effect on e-satisfaction. this implies that e-shoppers feel highly satisfied with the freedom of time and space which wall defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumers e-satisfaction. And the fact that consumers have tendency to trust more the shopping mall where they purchased more than once in the past means that transaction security also requires special consideration. This study was investigated with focused on shopping mall site itself, therefore the major parts of critical success factors from site design to implementation could be discussed and get helpful suggestions."
text2 = "This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market; especially the survey was strictly carried out only for the consumers who had ever experienced e-shopping or transaction more than once. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had positive effect on e-satisfaction. This implies that e-shoppers feel highly satisfied with the freedom of time and space which was defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumer's e-satisfaction. And the fact that consumers have tendency to trust more the shopping mall where they purchased more than once in the past means that transaction security also requires special consideration. This study was investigated with focused on shopping mall site itself, therefore the major parts of critical success factors from site design to implementation could be discussed and get helpful suggestions."

In [2]:
text1

'This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had position effect on e-satisfaction. this implies that e-shoppers feel highly satisfied with the freedom of time and space which wall defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumers e-satisfaction. And the fact that consumers have tendency to trust more the shopping mall where they purchased more than once in the past means that trans

In [3]:
text2

"This study has been performed to investigate and analyze the affecting factors of e-Satisfaction focused on internet shopping malls in online e-commerce market; especially the survey was strictly carried out only for the consumers who had ever experienced e-shopping or transaction more than once. As a result of study, it was detected that those factors of convenience, site design, product assortment information offering had positive effect on e-satisfaction. This implies that e-shoppers feel highly satisfied with the freedom of time and space which was defined as convenience factor. It also means that major consumers of local internet shopping malls feel satisfied if a shopping mall site is well-formed and supports fast searching functions. In addition, diversity of products and appropriate level of inventory to general availability of service and product, detailed information on product, and other additional information supports were also proved to affect consumer's e-satisfaction. A

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
tf = TfidfVectorizer()

In [12]:
reviews_tf = tf.fit_transform([text2])
reviews_tf

<1x123 sparse matrix of type '<class 'numpy.float64'>'
	with 123 stored elements in Compressed Sparse Row format>

In [14]:
tf.get_feature_names_out()

array(['addition', 'additional', 'affect', 'affecting', 'also', 'analyze',
       'and', 'appropriate', 'as', 'assortment', 'availability', 'be',
       'been', 'carried', 'commerce', 'consideration', 'consumer',
       'consumers', 'convenience', 'could', 'critical', 'defined',
       'design', 'detailed', 'detected', 'discussed', 'diversity',
       'effect', 'especially', 'ever', 'experienced', 'fact', 'factor',
       'factors', 'fast', 'feel', 'focused', 'for', 'formed', 'freedom',
       'from', 'functions', 'general', 'get', 'had', 'has', 'have',
       'helpful', 'highly', 'if', 'implementation', 'implies', 'in',
       'information', 'internet', 'inventory', 'investigate',
       'investigated', 'is', 'it', 'itself', 'level', 'local', 'major',
       'mall', 'malls', 'market', 'means', 'more', 'of', 'offering', 'on',
       'once', 'online', 'only', 'or', 'other', 'out', 'parts', 'past',
       'performed', 'positive', 'product', 'products', 'proved',
       'purchased', 'requ

In [15]:
reviews_tf.toarray()

array([[0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 , 0.12288479,
        0.0409616 , 0.32769277, 0.0409616 , 0.08192319, 0.0409616 ,
        0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 ,
        0.0409616 , 0.0409616 , 0.12288479, 0.08192319, 0.0409616 ,
        0.0409616 , 0.0409616 , 0.08192319, 0.0409616 , 0.0409616 ,
        0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 ,
        0.0409616 , 0.0409616 , 0.0409616 , 0.12288479, 0.0409616 ,
        0.08192319, 0.08192319, 0.0409616 , 0.0409616 , 0.0409616 ,
        0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 , 0.08192319,
        0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 ,
        0.0409616 , 0.0409616 , 0.12288479, 0.12288479, 0.08192319,
        0.0409616 , 0.0409616 , 0.0409616 , 0.0409616 , 0.08192319,
        0.0409616 , 0.0409616 , 0.0409616 , 0.08192319, 0.12288479,
        0.08192319, 0.0409616 , 0.08192319, 0.12288479, 0.36865436,
        0.0409616 , 0.16384638, 0.08192319, 0.04

In [16]:
compare_tf = tf.transform([text1])
compare_tf

<1x123 sparse matrix of type '<class 'numpy.float64'>'
	with 110 stored elements in Compressed Sparse Row format>

In [17]:
compare_tf

<1x123 sparse matrix of type '<class 'numpy.float64'>'
	with 110 stored elements in Compressed Sparse Row format>

In [18]:
compare_tf.toarray()

array([[0.04406526, 0.04406526, 0.04406526, 0.04406526, 0.13219579,
        0.04406526, 0.35252212, 0.04406526, 0.08813053, 0.04406526,
        0.04406526, 0.04406526, 0.04406526, 0.        , 0.04406526,
        0.04406526, 0.        , 0.13219579, 0.08813053, 0.04406526,
        0.04406526, 0.04406526, 0.08813053, 0.04406526, 0.04406526,
        0.04406526, 0.04406526, 0.04406526, 0.        , 0.        ,
        0.        , 0.04406526, 0.04406526, 0.13219579, 0.04406526,
        0.08813053, 0.08813053, 0.        , 0.04406526, 0.04406526,
        0.04406526, 0.04406526, 0.04406526, 0.04406526, 0.04406526,
        0.04406526, 0.04406526, 0.04406526, 0.04406526, 0.04406526,
        0.04406526, 0.04406526, 0.13219579, 0.13219579, 0.08813053,
        0.04406526, 0.04406526, 0.04406526, 0.04406526, 0.08813053,
        0.04406526, 0.04406526, 0.04406526, 0.08813053, 0.13219579,
        0.08813053, 0.04406526, 0.08813053, 0.08813053, 0.39658738,
        0.04406526, 0.17626106, 0.04406526, 0.04

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

sim_result_tf = cosine_similarity(compare_tf, reviews_tf)
sim_result_tf

array([[0.9783011]])

In [1]:
from sklearn.metrics.pairwise import cosine_similarity