In [1]:
import json
from sklearn.datasets import fetch_20newsgroups

In [2]:
categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space']

In [3]:
newsgroups_train = fetch_20newsgroups(
    subset='train',
    remove=('headers', 'footers', 'quotes'),
    categories=categories
)

In [4]:
newsgroups_test = fetch_20newsgroups(
    subset='test',
    remove=('headers', 'footers', 'quotes'),
    categories=categories
)

In [9]:
newsgroups_train.target

array([1, 3, 2, ..., 1, 0, 1], dtype=int64)

In [11]:
newsgroups_train.target_names

['alt.atheism', 'comp.graphics', 'sci.space', 'talk.religion.misc']

In [14]:
len(newsgroups_train.data)

2034

In [16]:
newsgroups_test.target

array([2, 1, 1, ..., 3, 1, 1], dtype=int64)

In [19]:
newsgroups_test.target_names

['alt.atheism', 'comp.graphics', 'sci.space', 'talk.religion.misc']

In [18]:
len(newsgroups_test.data)

1353

In [21]:
newsgroups_train.data[0]

"Hi,\n\nI've noticed that if you only save a model (with all your mapping planes\npositioned carefully) to a .3DS file that when you reload it after restarting\n3DS, they are given a default position and orientation.  But if you save\nto a .PRJ file their positions/orientation are preserved.  Does anyone\nknow why this information is not stored in the .3DS file?  Nothing is\nexplicitly said in the manual about saving texture rules in the .PRJ file. \nI'd like to be able to read the texture rule information, does anyone have \nthe format for the .PRJ file?\n\nIs the .CEL file format available from somewhere?\n\nRych"

In [32]:
newsgroups_train.target[0]

1

In [33]:
newsgroups_test.data[0]

'TRry the SKywatch project in  Arizona.'

In [34]:
newsgroups_test.data[0]

'TRry the SKywatch project in  Arizona.'

In [35]:
newsgroups_test.target[0]

2

### 5.1.2 카운트 기반 특성 추출 (97page)

In [45]:
X_train = newsgroups_train.data
y_train = newsgroups_train.target

X_test = newsgroups_test.data
y_test = newsgroups_test.target

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
cv = CountVectorizer(max_features=2000, min_df=5, max_df=0.5)

In [48]:
X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

In [49]:
X_train_cv.shape

(2034, 2000)

In [50]:
X_test_cv.shape

(1353, 2000)

In [51]:
cv.get_feature_names_out()

array(['00', '000', '01', ..., 'yourself', 'zero', 'zip'], dtype=object)

In [55]:
X_train_cv[0].toarray()[0, :100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [60]:
from sklearn.naive_bayes import MultinomialNB

In [61]:
NB_clf = MultinomialNB()

In [62]:
NB_clf

MultinomialNB()

In [63]:
NB_clf.fit(X_train_cv, y_train)

MultinomialNB()

In [66]:
NB_clf.score(X_train_cv, y_train)

0.823992133726647

In [67]:
NB_clf.score(X_test_cv, y_test)

0.7324464153732446

In [68]:
print(X_test[0], y_test[0])

TRry the SKywatch project in  Arizona. 2


In [69]:
print(X_test[1], y_test[1])

The Vatican library recently made a tour of the US.
 Can anyone help me in finding a FTP site where this collection is 
 available. 1


In [91]:
NB_clf.predict(X_test_cv[:2])

array([2, 1], dtype=int64)

In [92]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [93]:
tfidf = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.5)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [96]:
X_test_tfidf.shape

(1353, 2000)

In [97]:
X_train_tfidf.shape

(2034, 2000)

In [99]:
NB_clf = MultinomialNB()
NB_clf.fit(X_train_tfidf, y_train)

MultinomialNB()

In [100]:
NB_clf.score(X_train_tfidf, y_train)

0.8618485742379548

In [101]:
NB_clf.score(X_test_tfidf, y_test)

0.7413155949741316

In [109]:
import numpy as np

def top10_features(classifier, vectorizer, categories):
    features_names = np.asarray(vectorizer.get_feature_names_out())
    for i, category in enumerate(categories):

        top10 = np.argsort(-classifier.coef_[i])[:10]
        print(category, ", ".join(features_names[top10]))

In [106]:
tfidf.get_feature_names_out()

array(['00', '000', '01', ..., 'yourself', 'zero', 'zip'], dtype=object)

In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
LR_clf = LogisticRegression()

In [113]:
LR_clf.fit(X_train_tfidf, y_train)

LogisticRegression()

In [114]:
LR_clf.score(X_train_tfidf, y_train)

0.9296951819075713

In [115]:
LR_clf.score(X_test_tfidf, y_test)

0.7339246119733924

In [116]:
from sklearn.linear_model import RidgeClassifier

In [117]:
ridge_clf = RidgeClassifier()

In [118]:
ridge_clf.fit(X_train_tfidf, y_train)

RidgeClassifier()

In [119]:
ridge_clf.score(X_train_tfidf, y_train)

0.95968534906588

In [120]:
ridge_clf.score(X_test_tfidf, y_test)

0.7346637102734663

In [121]:
import numpy as np

In [122]:
from sklearn.model_selection import train_test_split

In [124]:
X_train_ridge, X_val_ridge, y_train_ridge, y_val_ridge = train_test_split(X_train_tfidf, y_train, test_size=0.2, random_state=42)

In [127]:
max_score = 0
max_alpha = 0
for alpha in np.arange(0.1, 10, 0.1):
    ridge_clf = RidgeClassifier(alpha=alpha)
    ridge_clf.fit(X_train_ridge, y_train_ridge)
    score = ridge_clf.score(X_val_ridge, y_val_ridge)
    if score > max_score:
        max_score = score
        max_alpha = alpha

In [129]:
max_score

0.8255528255528255

In [128]:
max_alpha

1.6

In [130]:
ridge_clf = RidgeClassifier(alpha=1.6)
ridge_clf.fit(X_train_tfidf, y_train)
ridge_clf.score(X_test_tfidf, y_test)

0.7390983000739099

In [131]:
top10_features(ridge_clf, tfidf, newsgroups_train.target_names)

alt.atheism bobby, religion, atheism, atheists, motto, punishment, islam, deletion, islamic, satan
comp.graphics graphics, computer, 3d, file, image, hi, 42, using, screen, looking
sci.space space, orbit, nasa, spacecraft, moon, sci, launch, flight, funding, idea
talk.religion.misc christian, christians, fbi, blood, order, jesus, objective, children, christ, hudson


In [193]:
lasso_clf = LogisticRegression(penalty='l1', solver='liblinear', C=1)
lasso_clf.fit(X_train_tfidf, y_train)
lasso_clf.score(X_test_tfidf, y_test)

0.7235772357723578

In [203]:
lasso_clf.coef_

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.48716557, 0.        ,
        0.        ]])

In [204]:
top10_features(lasso_clf, tfidf, newsgroups_train.target_names)

alt.atheism bobby, atheism, atheists, islam, religion, islamic, motto, atheist, satan, vice
comp.graphics graphics, image, 3d, file, computer, hi, video, files, looking, sphere
sci.space space, orbit, launch, nasa, spacecraft, flight, moon, dc, shuttle, solar
talk.religion.misc fbi, christian, christians, christ, order, jesus, children, objective, context, blood


In [205]:
from sklearn.linear_model import Lasso

In [221]:
lasso_clf = Lasso(alpha=1)
lasso_clf.fit(X_train_tfidf, y_train)
lasso_clf.score(X_test_tfidf, y_test)

-3.904573553370483e-08

In [222]:
lasso_clf

Lasso(alpha=1)

In [228]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [232]:
tree = DecisionTreeClassifier(random_state=7)
tree.fit(X_train_tfidf, y_train)

DecisionTreeClassifier(random_state=7)

In [233]:
print(tree.score(X_train_tfidf, y_train))
print(tree.score(X_test_tfidf, y_test))

0.9773844641101278
0.5358462675535847


In [234]:
forest = RandomForestClassifier(random_state=7)
forest.fit(X_train_tfidf, y_train)

RandomForestClassifier(random_state=7)

In [235]:
print(forest.score(X_train_tfidf, y_train))
print(forest.score(X_test_tfidf, y_test))

0.9773844641101278
0.6851441241685144


In [236]:
gb = GradientBoostingClassifier(random_state=7)
gb.fit(X_train_tfidf, y_train)

GradientBoostingClassifier(random_state=7)

In [237]:
print(gb.score(X_train_tfidf, y_train))
print(gb.score(X_test_tfidf, y_test))

0.932645034414946
0.6962305986696231


In [238]:
gb.feature_importances_

array([0.        , 0.        , 0.00018793, ..., 0.00321606, 0.        ,
       0.        ])

In [240]:
for a, b in zip(tfidf.get_feature_names_out(), gb.feature_importances_):
    print(a, b)

00 0.0
000 0.0
01 0.0001879332127649151
04 0.0
05 0.0
10 9.883607872510905e-05
100 0.0
1000 6.473751341709295e-07
11 0.0
12 0.0
128 0.0
129 0.0
13 2.008425648829126e-07
130 0.0
14 0.0
15 2.516124350974213e-07
16 0.0
17 0.0
18 0.0
19 0.0
1987 0.0
1988 0.0
1989 0.0
1990 0.0
1991 0.0
1992 0.0
1993 7.276725872058238e-05
20 0.0
200 0.0
202 0.0
21 1.412171476439304e-06
22 0.0
23 0.0008565498604531021
24 0.0009253411970573228
25 0.0
256 0.0026941947928842995
26 0.0005861303016457679
27 0.0
28 0.0
2d 0.0
30 0.0006247876254295323
300 0.0
31 0.0
32 6.111288453377536e-05
33 0.0
34 0.0
35 0.0
39 0.0
3d 0.007819020701620837
40 0.0
400 0.0
42 0.0006758577227103907
45 0.0
50 0.0
500 0.0
60 0.0
600 0.0
65 0.0
70 0.0
75 0.0
80 0.0
800 0.0
90 0.0
900 0.0
91 0.0
92 4.253484346946885e-06
93 0.0
95 0.0
_the 0.0
ability 0.0
able 2.2247381322709356e-05
abortion 0.0013365771956900937
about 0.004021200741750711
above 0.0001852456871647147
absolute 0.0
absolutely 0.0
ac 0.0
accept 2.216823186325628e-09
acceptab

In [243]:
for x in np.argsort(-gb.feature_importances_):
    print(tfidf.get_feature_names_out()[x], gb.feature_importances_[x])

space 0.12606815556503398
graphics 0.07955738535484687
atheism 0.023543258791466362
thanks 0.023046507462732756
file 0.02055581240238831
orbit 0.020063273938036058
jesus 0.01814149212443511
god 0.017712702350040938
hi 0.016857094927865728
nasa 0.015308260768876465
image 0.015023452519852164
files 0.013797145686816017
christ 0.010426583770790022
moon 0.010376173054679735
bobby 0.010225361352506714
launch 0.010061136447910934
looking 0.009733618292917433
christian 0.009663039306452306
atheists 0.00940203835982551
christians 0.008981046753380316
fbi 0.008827368636033589
3d 0.007819020701620837
you 0.0077517919234373674
not 0.007515358150120414
islamic 0.007255118998822582
religion 0.007182617149762632
spacecraft 0.007074189152295396
flight 0.006899060277543797
computer 0.006698870635101263
islam 0.006529364772733121
ftp 0.0062457492372051055
color 0.005513872126424359
software 0.004918770389689074
atheist 0.004805134811116729
card 0.0047679402132682755
people 0.004624503816321023
koresh 0

### 5.6 성능을 높이는 방법

In [244]:
from nltk.corpus import stopwords
cachedStopWords = stopwords.words("english")

In [245]:
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
import re

In [246]:
RegTok = RegexpTokenizer("[\w']{3,}")
english_stops = set(stopwords.words('english'))

In [247]:
def tokenizer(text):
    tokens = RegTok.tokenize(text.lower())
    words = [word for word in tokens if (word not in english_stops) and len(word) > 2]
    features = list(map(lambda token: PorterStemmer().stem(token), words))
    return features


In [248]:
tfidf = TfidfVectorizer(tokenizer=tokenizer, max_features=2000, min_df=5, max_df=0.5)

In [251]:
X_train_tfidf = tfidf.fit_transform(X_train)

In [252]:
tfidf.get_feature_names_out()

array(['000', '100', '1000', ..., 'young', 'zero', 'zip'], dtype=object)

In [253]:
X_test_tfidf = tfidf.transform(X_test)

In [254]:
LR_clf = LogisticRegression()
LR_clf.fit(X_train_tfidf, y_train)

LogisticRegression()

In [255]:
LR_clf.score(X_train_tfidf, y_train)

0.9301868239921337

In [256]:
LR_clf.score(X_test_tfidf, y_test)

0.7509238728750924

In [257]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [258]:
tfidf = TfidfVectorizer(tokenizer=tokenizer)

In [259]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [260]:
X_train_tfidf.shape

(2034, 20085)

In [262]:
X_test_tfidf.shape

(1353, 20085)

In [263]:
ridge_clf = RidgeClassifier(alpha=2.4)
ridge_clf.fit(X_train_tfidf, y_train)

RidgeClassifier(alpha=2.4)

In [264]:
ridge_clf.score(X_train_tfidf,  y_train)

0.9680432645034415

In [265]:
ridge_clf.score(X_test_tfidf,  y_test)

0.7679231337767923

In [266]:
NB_clf = MultinomialNB(alpha=0.01)
NB_clf.fit(X_train_tfidf, y_train)

MultinomialNB(alpha=0.01)

In [267]:
NB_clf.score(X_train_tfidf, y_train)

0.9714847590953786

In [268]:
NB_clf.score(X_test_tfidf, y_test)

0.7930524759793053

### 5.7 카운트 기반의 문제점과 N-gram을 이용한 보완

In [270]:
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [271]:
chchedStopWords = stopwords.words("english")

In [293]:
tfidf = TfidfVectorizer(
    token_pattern="[a-zA-Z']{3,}",
    decode_error='ignore',
    lowercase=True,
    ngram_range=(1,3),
    stop_words=stopwords.words("english"),
    max_df=0.5,
    min_df=2
)

In [294]:
tfidf

TfidfVectorizer(decode_error='ignore', max_df=0.5, min_df=2, ngram_range=(1, 3),
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                token_pattern="[a-zA-Z']{3,}")

In [295]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [296]:
X_train_tfidf.shape

(2034, 32943)

In [297]:
X_test_tfidf.shape

(1353, 32943)

In [298]:
from sklearn.linear_model import RidgeClassifier
ridge_clf = RidgeClassifier()
ridge_clf.fit(X_train_tfidf, y_train)

RidgeClassifier()

In [299]:
ridge_clf.score(X_train_tfidf, y_train)

0.976401179941003

In [300]:
ridge_clf.score(X_test_tfidf, y_test)

0.7745750184774575

In [301]:
[word for word in tfidf.get_feature_names_out() if len(word) >= 3]

["'bout",
 "'burning'",
 "'cause",
 "'cause can't",
 "'cos",
 "'course",
 "'em",
 "'em better",
 "'em better shots",
 "'expected",
 "'expected errors'",
 "'expected errors' basically",
 "'fast'",
 "'if",
 "'karla'",
 "'karla' next",
 "'karla' next one",
 "'no",
 "'nodis'",
 "'nodis' password",
 "'nodis' password also",
 "'official",
 "'official doctrine",
 "'official doctrine think",
 "'ok",
 "'ok see",
 "'ok see warning",
 "'one",
 "'sci",
 "'sci astro'",
 "'smiley'",
 "'the",
 "'what's",
 "'what's moonbase",
 "'what's moonbase good",
 "'yes",
 "'you",
 "'zlumber",
 'aantal',
 'aao',
 'aas',
 'aas american',
 'aas american astronautical',
 'abandon',
 'abandoned',
 'abc',
 'abilities',
 'ability',
 'ability means',
 'ability means infallible',
 'ability pass',
 'able',
 'able accept',
 'able accept donations',
 'able afford',
 'able afford stuff',
 'able control',
 'able convince',
 'able draw',
 'able establish',
 'able find',
 'able get',
 'able help',
 'able import',
 'able judge',

### 5.8 한국어 문서의 분류

In [304]:
import pandas as pd
df = pd.read_csv('daum_movie_review.csv')
df.head(5)

review  rating        date  \
0                             돈 들인건 티가 나지만 보는 내내 하품만       1  2018.10.29   
1       몰입할수밖에 없다. 어렵게 생각할 필요없다. 내가 전투에 참여한듯 손에 땀이남.      10  2018.10.26   
2  이전 작품에 비해 더 화려하고 스케일도 커졌지만.... 전국 맛집의 음식들을 한데 ...       8  2018.10.24   
3                                이 정도면 볼만하다고 할 수 있음!       8  2018.10.22   
4                                               재미있다      10  2018.10.20   

    title  
0  인피니티 워  
1  인피니티 워  
2  인피니티 워  
3  인피니티 워  
4  인피니티 워

In [310]:
df.title.value_counts()

신과함께      4947
택시운전사     2322
인피니티 워    2042
범죄도시      1939
곤지암       1547
라라랜드      1150
코코         778
Name: title, dtype: int64

In [311]:
from sklearn.model_selection import train_test_split

In [312]:
X_train, X_test, y_train, y_test = train_test_split(df.review, df.title, random_state=0)

In [313]:
len(X_train)

11043

In [317]:
X_train

3009                영상도 아름답고 음악도 좋았어요. 오랜만에 마음 따뜻해진 영화였어요.
8833     3단계에서 울었어요....ㅠㅠ 앞으로 4단계나 더 남았다는걸 알고 통곡할 뻔 했어요...
5244     Good... 착하게 살자.. 인간이 죄를 짓지 않을순없지만 죄를 지었으면 용서를 ...
6381     컴퓨터 그래픽~ 이 볼만하지만 중간 지점가면 지루해지고 마지막 반전이.... 신파!...
1766                                           잠못자고 볼 가치있음
                               ...                        
13123    5.18  민주화 운동의  상황을 실제로 찍은 영상을 토대로 연기하여 서로 번갈아가...
3264                                         공포영화냐 코메디 영화냐
9845                                      너네....까불지 말고 보라우
10799                                     윤계상 연기 쩔음!! 쵴오~~
2732                                       최고의 영화 중의 하나!!!
Name: review, Length: 11043, dtype: object

In [314]:
len(X_test)

3682

In [315]:
from konlpy.tag import Okt

In [316]:
okt = Okt()

In [318]:
okt.morphs(X_train[1])

['몰입',
 '할수밖에',
 '없다',
 '.',
 '어렵게',
 '생각',
 '할',
 '필요없다',
 '.',
 '내',
 '가',
 '전투',
 '에',
 '참여',
 '한',
 '듯',
 '손',
 '에',
 '땀',
 '이남',
 '.']

In [319]:
okt.nouns(X_train[1])

['몰입', '생각', '내', '전투', '참여', '듯', '손', '땀', '이남']

In [320]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [338]:
tfidf = TfidfVectorizer(
    tokenizer=okt.morphs,
    max_features=2000,
    min_df=5,
    max_df=0.5
)

In [339]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [340]:
clf = LogisticRegression(max_iter=1000)

In [343]:
clf.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [344]:
clf.score(X_train_tfidf, y_train)

0.7768722267499774

In [345]:
clf.score(X_test_tfidf, y_test)

0.694731124388919

In [330]:
y_test[:10]

10711     범죄도시
9848      범죄도시
14545       코코
9017      신과함께
8659      신과함께
11692    택시운전사
5911      신과함께
6409      신과함께
11275     범죄도시
10818     범죄도시
Name: title, dtype: object

In [332]:
clf.predict(X_test_tfidf[:10])

array(['신과함께', '범죄도시', '코코', '신과함께', '신과함께', '택시운전사', '신과함께', '신과함께',
       '신과함께', '인피니티 워'], dtype=object)

In [337]:
for a, b, c in zip(y_test[:10], clf.predict(X_test_tfidf[:10]), X_test[:10]):
    print(a, b, c)

범죄도시 신과함께 오랜만에 잼나는 영화 봤습니다.  다음에 더 재미있는 영화 기대하겠습니다.
범죄도시 범죄도시 조연들이 눈에 박힌다. 간만에 집중 ㅎ
코코 코코 대감동을 선사. 인사이드 아웃을 잇는 픽사의 감동스토리. 신과함께의 멕시코판이라고나할까요??
신과함께 신과함께 돈이 안아까웠던 영화ᆞᆞ  정말 좋았다
신과함께 신과함께 역시 김용화감독이 영화는 잘 만들어요. 이제 VFX 제작 부문도 헐리우드 수준 이상입니다.
택시운전사 택시운전사 민주화를 위해 힘써주신 분들께 감사하는 마음으로 살아야겠다.
신과함께 신과함께 잠만 자다 왔음
신과함께 신과함께 오랜만에 잼있고 좋은 영화를 봤다
범죄도시 신과함께 잼남
범죄도시 인피니티 워 대박~~


In [346]:
def twit_tokenizer(text):
    target_tags = ['Noun', 'Verb', 'Adjective']
    result = []
    for word, tag in okt.pos(text, norm=True, stem=True):
        if tag in target_tags:
            result.append(word)
    return result

In [349]:
def twit_tokenizer2(text):
    #target_tags = ['Noun', 'Verb', 'Adjective']
    result = []
    for word, tag in okt.pos(text, norm=True, stem=True):
        result.append('/'.join([word, tag]))
    return result

In [352]:
def twit_tokenizer3(text):
    target_tags = ['Noun', 'Verb', 'Adjective']
    result = []
    for word, tag in okt.pos(text, norm=True, stem=True):
        if tag in target_tags:
            result.append('/'.join([word, tag]))
    return result

In [353]:
tfidf = TfidfVectorizer(
    tokenizer=twit_tokenizer3,
    max_features=2000,
    min_df=5,
    max_df=0.5
)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [348]:
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_tfidf, y_train)
print(clf.score(X_train_tfidf, y_train))
print(clf.score(X_test_tfidf, y_test))

0.7837544145612605
0.7121129820749592


In [351]:
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_tfidf, y_train)
print(clf.score(X_train_tfidf, y_train))
print(clf.score(X_test_tfidf, y_test))

0.789097165625283
0.7180879956545356


In [354]:
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_tfidf, y_train)
print(clf.score(X_train_tfidf, y_train))
print(clf.score(X_test_tfidf, y_test))

0.7837544145612605
0.7129277566539924


In [355]:
#130p